### ISSUE TITLE
NewOffiAccount 方法没有赋值AESKEY和Token

### ISSUE THREAD

**Issue by lscgzwd** [fastwego/wxopen#3]
NewOffiAccount 方法没有赋值AESKEY和Token，导致公众号消息解密报错

···
/*
创建公众号实例
*/
func (platform *Platform) NewOffiAccount(appid string) (offiAccount *offiaccount.OffiAccount, err error) {
	offiAccount = offiaccount.New(offiaccount.Config{
		Appid: appid,
	})

	offiAccount.AccessToken.GetAccessTokenHandler = func(ctx *offiaccount.OffiAccount) (accessToken string, err error) {
		return platform.GetAuthorizerAccessTokenHandler(platform, ctx.Config.Appid)
	}

	offiAccount.AccessToken.NoticeAccessTokenExpireHandler = func(ctx *offiaccount.OffiAccount) (err error) {
		return platform.NoticeAuthorizerAccessTokenExpireHandler(platform, ctx.Config.Appid)
	}

	return
}
···

小程序可能有一样的问题，需要把第三平台的消息加密key和验证token赋值过去

**Comment by Ceelog** [comment]
已经更新修复了 dc1c896433b7ce90c58a3a5975d0860412d48317
